version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: surveys
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "3307:3306"
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: localhost
  redis-account:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql
    ports: 
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./server:/app
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - 3000:3000
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql
      environment:
        ADMINER_DEFAULT_SERVER: mysql
volumes:
  mysql:
  redisdata: